import {
  Ab,
  Abr,
  Cd,
  Cgs,
  Cm,
  Cmaif,
  Cmsts,
  Cond,
  Cty,
  Da,
  De,
  Ed,
  Ega,
  Ej,
  Ejc,
  Ejf,
  Ejg,
  Ejh,
  Eji,
  Ejl,
  Ejm,
  Ejn,
  Ejs,
  Ejt,
  Eju,
  Ejv,
  Etm,
  Etn,
  Ets,
  Eu,
  Ev,
  Evdet,
  Evesc,
  Evgid,
  Evgrp,
  Evhst,
  Evipa,
  Evpid,
  Evsfr,
  Evsid,
  Evsms,
  Evspl,
  Evsrc,
  Evsrt,
  Evssv,
  Evtmc,
  Evuid,
  Evusr,
  Evwfr,
  Evwid,
  Evwms,
  Evwsv,
  Ex,
  F,
  Fd,
  Flco,
  Flwc,
  Flwf,
  Flwi,
  Fxg,
  Gty,
  Ha,
  Htcdm,
  Htcfl,
  Htexm,
  Htknd,
  Htrbf,
  Htrhf,
  Htrqf,
  Htrqm,
  Htrqu,
  Htspt,
  Htstf,
  Jc,
  Jd,
  Jdf,
  Jty,
  Lfcre,
  Lfdft,
  Lffnm,
  Lfhds,
  Lfmks,
  Lfmxl,
  Lfrft,
  Lfsiv,
  Lfsrc,
  Lftpd,
  Mcs,
  Mh,
  Mlafl,
  Mlatf,
  Mlftx,
  Mllst,
  Mlprf,
  Mlsav,
  Mlsfd,
  Mlstx,
  Mm,
  Mp,
  Mqcor,
  Mqdsc,
  Mqeqn,
  Mqhld,
  Mqmdl,
  Mqmdn,
  Mqmfn,
  Mqmgr,
  Mqpgm,
  Mqpri,
  Mqprm,
  Mqque,
  Mqsfn,
  Ms,
  Msapl,
  Mshld,
  Msjnl,
  Mslbl,
  Mslmt,
  Msmod,
  Mspri,
  Msqlb,
  Msqpt,
  Msrer,
  Mssvf,
  Mstfn,
  Msttp,
  Msunr,
  Mu,
  Ncex,
  Nchn,
  Ncl,
  Ncn,
  Ncr,
  Ncs,
  Ncsv,
  Nmg,
  Ntcls,
  Ntdis,
  Nteid,
  Ntevt,
  Ntlgt,
  Ntncl,
  Ntnei,
  Ntnsr,
  Ntolg,
  Ntsrc,
  Pfm,
  Prm,
  Pwlf,
  Pwlt,
  Pwrf,
  Pwrh,
  Pwrn,
  Pwrp,
  Pwrr,
  Pwrw,
  Qm,
  Qu,
  Rec,
  Rei,
  Req,
  Rh,
  Rje,
  Rjs,
  Sc,
  Se,
  Sea,
  Si,
  So,
  Soa,
  Sz,
  T,
  Td1,
  Td2,
  Td3,
  Td4,
  Te,
  Tho,
  Tmitv,
  Ts1,
  Ts2,
  Ts3,
  Ts4,
  Uem,
  Un,
  Unit,
  Wkp,
  Wth,
} from "../parameters";
import { UnitEntity } from "../units/UnitEntity";
import { DEFAULTS } from "./Defaults";
import { buildOptionalParameter } from "./parameterHelpers";
import { ParamInternal } from "./parameter.types";

const createOptionalScalarBuilder = <T, P extends ParamInternal["parameter"]>(
  parameter: P,
  mapParam: (param: ParamInternal) => T,
  defaultRawValue?: string,
) => {
  return (unit: UnitEntity): T | undefined =>
    buildOptionalParameter(
      {
        unit: unit,
        parameter: parameter,
        defaultRawValue: defaultRawValue,
      },
      mapParam,
    );
};

const createRuntimeDefaultOptionalScalarBuilder = <
  T,
  P extends ParamInternal["parameter"],
>(
  parameter: P,
  mapParam: (param: ParamInternal) => T,
) => {
  return (unit: UnitEntity, defaultRawValue?: string): T | undefined =>
    buildOptionalParameter(
      {
        unit: unit,
        parameter: parameter,
        defaultRawValue: defaultRawValue,
      },
      mapParam,
    );
};

export const optionalScalarParameterBuilders = {
  ab: createOptionalScalarBuilder("ab", (param) => new Ab(param), DEFAULTS.Ab),
  abr: createOptionalScalarBuilder(
    "abr",
    (param) => new Abr(param),
    DEFAULTS.Abr,
  ),
  cd: createOptionalScalarBuilder("cd", (param) => new Cd(param), DEFAULTS.Cd),
  cgs: createOptionalScalarBuilder(
    "cgs",
    (param) => new Cgs(param),
    DEFAULTS.Cgs,
  ),
  cm: createOptionalScalarBuilder("cm", (param) => new Cm(param)),
  cmaif: createOptionalScalarBuilder("cmaif", (param) => new Cmaif(param)),
  cmsts: createOptionalScalarBuilder("cmsts", (param) => new Cmsts(param)),
  cond: createOptionalScalarBuilder(
    "cond",
    (param) => new Cond(param),
    DEFAULTS.Cond,
  ),
  cty: createOptionalScalarBuilder("cty", (param) => new Cty(param)),
  da: createOptionalScalarBuilder("da", (param) => new Da(param)),
  de: createOptionalScalarBuilder("de", (param) => new De(param), DEFAULTS.De),
  ed: createOptionalScalarBuilder("ed", (param) => new Ed(param)),
  ega: createOptionalScalarBuilder(
    "ega",
    (param) => new Ega(param),
    DEFAULTS.Ega,
  ),
  ej: createOptionalScalarBuilder("ej", (param) => new Ej(param), DEFAULTS.Ej),
  ejc: createOptionalScalarBuilder(
    "ejc",
    (param) => new Ejc(param),
    DEFAULTS.Ejc,
  ),
  ejf: createOptionalScalarBuilder("ejf", (param) => new Ejf(param)),
  ejg: createOptionalScalarBuilder("ejg", (param) => new Ejg(param)),
  ejh: createOptionalScalarBuilder("ejh", (param) => new Ejh(param)),
  eji: createOptionalScalarBuilder(
    "eji",
    (param) => new Eji(param),
    DEFAULTS.Eji,
  ),
  ejl: createOptionalScalarBuilder("ejl", (param) => new Ejl(param)),
  ejm: createOptionalScalarBuilder(
    "ejm",
    (param) => new Ejm(param),
    DEFAULTS.Ejm,
  ),
  ejn: createOptionalScalarBuilder("ejn", (param) => new Ejn(param)),
  ejs: createOptionalScalarBuilder("ejs", (param) => new Ejs(param)),
  ejt: createOptionalScalarBuilder("ejt", (param) => new Ejt(param)),
  eju: createOptionalScalarBuilder(
    "eju",
    (param) => new Eju(param),
    DEFAULTS.Eju,
  ),
  ejv: createOptionalScalarBuilder("ejv", (param) => new Ejv(param)),
  etm: createOptionalScalarBuilder("etm", (param) => new Etm(param)),
  etn: createOptionalScalarBuilder(
    "etn",
    (param) => new Etn(param),
    DEFAULTS.Etn,
  ),
  ets: createOptionalScalarBuilder(
    "ets",
    (param) => new Ets(param),
    DEFAULTS.Ets,
  ),
  eu: createOptionalScalarBuilder("eu", (param) => new Eu(param), DEFAULTS.Eu),
  ev: createOptionalScalarBuilder("ev", (param) => new Ev(param)),
  evdet: createOptionalScalarBuilder("evdet", (param) => new Evdet(param)),
  evesc: createOptionalScalarBuilder(
    "evesc",
    (param) => new Evesc(param),
    DEFAULTS.Evesc,
  ),
  evgid: createOptionalScalarBuilder("evgid", (param) => new Evgid(param)),
  evgrp: createOptionalScalarBuilder("evgrp", (param) => new Evgrp(param)),
  evhst: createOptionalScalarBuilder("evhst", (param) => new Evhst(param)),
  evipa: createOptionalScalarBuilder("evipa", (param) => new Evipa(param)),
  evpid: createOptionalScalarBuilder("evpid", (param) => new Evpid(param)),
  evsfr: createOptionalScalarBuilder("evsfr", (param) => new Evsfr(param)),
  evsid: createOptionalScalarBuilder("evsid", (param) => new Evsid(param)),
  evsms: createOptionalScalarBuilder("evsms", (param) => new Evsms(param)),
  evspl: createOptionalScalarBuilder(
    "evspl",
    (param) => new Evspl(param),
    DEFAULTS.Evspl,
  ),
  evsrc: createOptionalScalarBuilder(
    "evsrc",
    (param) => new Evsrc(param),
    DEFAULTS.Evsrc,
  ),
  evsrt: createOptionalScalarBuilder(
    "evsrt",
    (param) => new Evsrt(param),
    DEFAULTS.Evsrt,
  ),
  evssv: createOptionalScalarBuilder(
    "evssv",
    (param) => new Evssv(param),
    DEFAULTS.Evssv,
  ),
  evtmc: createOptionalScalarBuilder(
    "evtmc",
    (param) => new Evtmc(param),
    DEFAULTS.Evtmc,
  ),
  evuid: createOptionalScalarBuilder("evuid", (param) => new Evuid(param)),
  evusr: createOptionalScalarBuilder("evusr", (param) => new Evusr(param)),
  evwfr: createOptionalScalarBuilder("evwfr", (param) => new Evwfr(param)),
  evwid: createOptionalScalarBuilder("evwid", (param) => new Evwid(param)),
  evwms: createOptionalScalarBuilder("evwms", (param) => new Evwms(param)),
  evwsv: createOptionalScalarBuilder("evwsv", (param) => new Evwsv(param)),
  ex: createOptionalScalarBuilder("ex", (param) => new Ex(param)),
  f: createOptionalScalarBuilder("f", (param) => new F(param)),
  fd: createOptionalScalarBuilder("fd", (param) => new Fd(param)),
  flco: createOptionalScalarBuilder(
    "flco",
    (param) => new Flco(param),
    DEFAULTS.Flco,
  ),
  flwc: createOptionalScalarBuilder(
    "flwc",
    (param) => new Flwc(param),
    DEFAULTS.Flwc,
  ),
  flwf: createOptionalScalarBuilder("flwf", (param) => new Flwf(param)),
  flwi: createOptionalScalarBuilder(
    "flwi",
    (param) => new Flwi(param),
    DEFAULTS.Flwi,
  ),
  fxg: createOptionalScalarBuilder(
    "fxg",
    (param) => new Fxg(param),
    DEFAULTS.Fxg,
  ),
  gty: createOptionalScalarBuilder(
    "gty",
    (param) => new Gty(param),
    DEFAULTS.Gty,
  ),
  ha: createOptionalScalarBuilder("ha", (param) => new Ha(param), DEFAULTS.Ha),
  htcdm: createOptionalScalarBuilder("htcdm", (param) => new Htcdm(param)),
  htcfl: createOptionalScalarBuilder("htcfl", (param) => new Htcfl(param)),
  htexm: createOptionalScalarBuilder(
    "htexm",
    (param) => new Htexm(param),
    DEFAULTS.Htexm,
  ),
  htknd: createOptionalScalarBuilder(
    "htknd",
    (param) => new Htknd(param),
    DEFAULTS.Htknd,
  ),
  htrbf: createOptionalScalarBuilder("htrbf", (param) => new Htrbf(param)),
  htrhf: createOptionalScalarBuilder("htrhf", (param) => new Htrhf(param)),
  htrqf: createOptionalScalarBuilder("htrqf", (param) => new Htrqf(param)),
  htrqm: createOptionalScalarBuilder("htrqm", (param) => new Htrqm(param)),
  htrqu: createOptionalScalarBuilder("htrqu", (param) => new Htrqu(param)),
  htspt: createOptionalScalarBuilder(
    "htspt",
    (param) => new Htspt(param),
    DEFAULTS.Htspt,
  ),
  htstf: createOptionalScalarBuilder("htstf", (param) => new Htstf(param)),
  jc: createOptionalScalarBuilder("jc", (param) => new Jc(param)),
  jd: createOptionalScalarBuilder("jd", (param) => new Jd(param), DEFAULTS.Jd),
  jdf: createOptionalScalarBuilder("jdf", (param) => new Jdf(param)),
  jty: createOptionalScalarBuilder(
    "jty",
    (param) => new Jty(param),
    DEFAULTS.Jty,
  ),
  lfcre: createOptionalScalarBuilder("lfcre", (param) => new Lfcre(param)),
  lfdft: createOptionalScalarBuilder("lfdft", (param) => new Lfdft(param)),
  lffnm: createOptionalScalarBuilder("lffnm", (param) => new Lffnm(param)),
  lfhds: createOptionalScalarBuilder("lfhds", (param) => new Lfhds(param)),
  lfmks: createOptionalScalarBuilder("lfmks", (param) => new Lfmks(param)),
  lfmxl: createOptionalScalarBuilder("lfmxl", (param) => new Lfmxl(param)),
  lfrft: createOptionalScalarBuilder("lfrft", (param) => new Lfrft(param)),
  lfsiv: createOptionalScalarBuilder("lfsiv", (param) => new Lfsiv(param)),
  lfsrc: createOptionalScalarBuilder("lfsrc", (param) => new Lfsrc(param)),
  lftpd: createOptionalScalarBuilder("lftpd", (param) => new Lftpd(param)),
  mcs: createOptionalScalarBuilder(
    "mcs",
    (param) => new Mcs(param),
    DEFAULTS.Mcs,
  ),
  mh: createOptionalScalarBuilder("mh", (param) => new Mh(param)),
  mlafl: createOptionalScalarBuilder("mlafl", (param) => new Mlafl(param)),
  mlatf: createOptionalScalarBuilder("mlatf", (param) => new Mlatf(param)),
  mlftx: createOptionalScalarBuilder("mlftx", (param) => new Mlftx(param)),
  mllst: createOptionalScalarBuilder("mllst", (param) => new Mllst(param)),
  mlprf: createOptionalScalarBuilder("mlprf", (param) => new Mlprf(param)),
  mlsav: createOptionalScalarBuilder(
    "mlsav",
    (param) => new Mlsav(param),
    DEFAULTS.Mlsav,
  ),
  mlsfd: createOptionalScalarBuilder("mlsfd", (param) => new Mlsfd(param)),
  mlstx: createOptionalScalarBuilder("mlstx", (param) => new Mlstx(param)),
  mm: createOptionalScalarBuilder("mm", (param) => new Mm(param), DEFAULTS.Mm),
  mp: createOptionalScalarBuilder("mp", (param) => new Mp(param), DEFAULTS.Mp),
  mqcor: createOptionalScalarBuilder("mqcor", (param) => new Mqcor(param)),
  mqdsc: createOptionalScalarBuilder("mqdsc", (param) => new Mqdsc(param)),
  mqeqn: createOptionalScalarBuilder("mqeqn", (param) => new Mqeqn(param)),
  mqhld: createOptionalScalarBuilder("mqhld", (param) => new Mqhld(param)),
  mqmdl: createOptionalScalarBuilder("mqmdl", (param) => new Mqmdl(param)),
  mqmdn: createOptionalScalarBuilder("mqmdn", (param) => new Mqmdn(param)),
  mqmfn: createOptionalScalarBuilder("mqmfn", (param) => new Mqmfn(param)),
  mqmgr: createOptionalScalarBuilder("mqmgr", (param) => new Mqmgr(param)),
  mqpgm: createOptionalScalarBuilder("mqpgm", (param) => new Mqpgm(param)),
  mqpri: createOptionalScalarBuilder("mqpri", (param) => new Mqpri(param)),
  mqprm: createOptionalScalarBuilder("mqprm", (param) => new Mqprm(param)),
  mqque: createOptionalScalarBuilder("mqque", (param) => new Mqque(param)),
  mqsfn: createOptionalScalarBuilder("mqsfn", (param) => new Mqsfn(param)),
  ms: createOptionalScalarBuilder("ms", (param) => new Ms(param), DEFAULTS.Ms),
  msapl: createOptionalScalarBuilder("msapl", (param) => new Msapl(param)),
  mshld: createOptionalScalarBuilder("mshld", (param) => new Mshld(param)),
  msjnl: createOptionalScalarBuilder("msjnl", (param) => new Msjnl(param)),
  mslbl: createOptionalScalarBuilder("mslbl", (param) => new Mslbl(param)),
  mslmt: createOptionalScalarBuilder("mslmt", (param) => new Mslmt(param)),
  msmod: createOptionalScalarBuilder("msmod", (param) => new Msmod(param)),
  mspri: createOptionalScalarBuilder("mspri", (param) => new Mspri(param)),
  msqlb: createOptionalScalarBuilder("msqlb", (param) => new Msqlb(param)),
  msqpt: createOptionalScalarBuilder("msqpt", (param) => new Msqpt(param)),
  msrer: createOptionalScalarBuilder("msrer", (param) => new Msrer(param)),
  mssvf: createOptionalScalarBuilder("mssvf", (param) => new Mssvf(param)),
  mstfn: createOptionalScalarBuilder("mstfn", (param) => new Mstfn(param)),
  msttp: createOptionalScalarBuilder("msttp", (param) => new Msttp(param)),
  msunr: createOptionalScalarBuilder("msunr", (param) => new Msunr(param)),
  mu: createOptionalScalarBuilder("mu", (param) => new Mu(param)),
  ncex: createRuntimeDefaultOptionalScalarBuilder(
    "ncex",
    (param) => new Ncex(param),
  ),
  nchn: createOptionalScalarBuilder("nchn", (param) => new Nchn(param)),
  ncl: createRuntimeDefaultOptionalScalarBuilder(
    "ncl",
    (param) => new Ncl(param),
  ),
  ncn: createOptionalScalarBuilder("ncn", (param) => new Ncn(param)),
  ncr: createOptionalScalarBuilder("ncr", (param) => new Ncr(param)),
  ncs: createRuntimeDefaultOptionalScalarBuilder(
    "ncs",
    (param) => new Ncs(param),
  ),
  ncsv: createOptionalScalarBuilder("ncsv", (param) => new Ncsv(param)),
  nmg: createOptionalScalarBuilder(
    "nmg",
    (param) => new Nmg(param),
    DEFAULTS.Nmg,
  ),
  ntcls: createOptionalScalarBuilder("ntcls", (param) => new Ntcls(param)),
  ntdis: createOptionalScalarBuilder("ntdis", (param) => new Ntdis(param)),
  nteid: createOptionalScalarBuilder("nteid", (param) => new Nteid(param)),
  ntevt: createOptionalScalarBuilder("ntevt", (param) => new Ntevt(param)),
  ntlgt: createOptionalScalarBuilder("ntlgt", (param) => new Ntlgt(param)),
  ntncl: createOptionalScalarBuilder("ntncl", (param) => new Ntncl(param)),
  ntnei: createOptionalScalarBuilder("ntnei", (param) => new Ntnei(param)),
  ntnsr: createOptionalScalarBuilder("ntnsr", (param) => new Ntnsr(param)),
  ntolg: createOptionalScalarBuilder("ntolg", (param) => new Ntolg(param)),
  ntsrc: createOptionalScalarBuilder("ntsrc", (param) => new Ntsrc(param)),
  pfm: createOptionalScalarBuilder(
    "pfm",
    (param) => new Pfm(param),
    DEFAULTS.Pfm,
  ),
  prm: createOptionalScalarBuilder("prm", (param) => new Prm(param)),
  pwlf: createOptionalScalarBuilder("pwlf", (param) => new Pwlf(param)),
  pwlt: createOptionalScalarBuilder("pwlt", (param) => new Pwlt(param)),
  pwrf: createOptionalScalarBuilder("pwrf", (param) => new Pwrf(param)),
  pwrh: createOptionalScalarBuilder("pwrh", (param) => new Pwrh(param)),
  pwrn: createOptionalScalarBuilder("pwrn", (param) => new Pwrn(param)),
  pwrp: createOptionalScalarBuilder("pwrp", (param) => new Pwrp(param)),
  pwrr: createOptionalScalarBuilder("pwrr", (param) => new Pwrr(param)),
  pwrw: createOptionalScalarBuilder("pwrw", (param) => new Pwrw(param)),
  qm: createOptionalScalarBuilder("qm", (param) => new Qm(param)),
  qu: createOptionalScalarBuilder("qu", (param) => new Qu(param)),
  rec: createOptionalScalarBuilder(
    "rec",
    (param) => new Rec(param),
    DEFAULTS.Rec,
  ),
  rei: createOptionalScalarBuilder(
    "rei",
    (param) => new Rei(param),
    DEFAULTS.Rei,
  ),
  req: createOptionalScalarBuilder("req", (param) => new Req(param)),
  rh: createOptionalScalarBuilder("rh", (param) => new Rh(param)),
  rje: createOptionalScalarBuilder("rje", (param) => new Rje(param)),
  rjs: createOptionalScalarBuilder("rjs", (param) => new Rjs(param)),
  sc: createOptionalScalarBuilder("sc", (param) => new Sc(param)),
  se: createOptionalScalarBuilder("se", (param) => new Se(param)),
  sea: createOptionalScalarBuilder(
    "sea",
    (param) => new Sea(param),
    DEFAULTS.Sea,
  ),
  si: createOptionalScalarBuilder("si", (param) => new Si(param)),
  so: createOptionalScalarBuilder("so", (param) => new So(param)),
  soa: createOptionalScalarBuilder(
    "soa",
    (param) => new Soa(param),
    DEFAULTS.Soa,
  ),
  sz: createOptionalScalarBuilder("sz", (param) => new Sz(param)),
  t: createOptionalScalarBuilder("t", (param) => new T(param)),
  td1: createOptionalScalarBuilder("td1", (param) => new Td1(param)),
  td2: createOptionalScalarBuilder("td2", (param) => new Td2(param)),
  td3: createOptionalScalarBuilder("td3", (param) => new Td3(param)),
  td4: createOptionalScalarBuilder("td4", (param) => new Td4(param)),
  te: createOptionalScalarBuilder("te", (param) => new Te(param)),
  tho: createOptionalScalarBuilder(
    "tho",
    (param) => new Tho(param),
    DEFAULTS.Tho,
  ),
  tmitv: createOptionalScalarBuilder("tmitv", (param) => new Tmitv(param)),
  ts1: createOptionalScalarBuilder("ts1", (param) => new Ts1(param)),
  ts2: createOptionalScalarBuilder("ts2", (param) => new Ts2(param)),
  ts3: createOptionalScalarBuilder("ts3", (param) => new Ts3(param)),
  ts4: createOptionalScalarBuilder("ts4", (param) => new Ts4(param)),
  uem: createOptionalScalarBuilder(
    "uem",
    (param) => new Uem(param),
    DEFAULTS.Uem,
  ),
  un: createOptionalScalarBuilder("un", (param) => new Un(param)),
  unit: createOptionalScalarBuilder("unit", (param) => new Unit(param)),
  wkp: createOptionalScalarBuilder("wkp", (param) => new Wkp(param)),
  wth: createOptionalScalarBuilder("wt", (param) => new Wth(param)),
} as const;
